=== CrispySteak/webTechFinalProject/scoreformat.dtd
<!DOCTYPE highscores
[
<!ELEMENT list(score*)>
<!ELEMENT score (username,difficulty,time)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT time (#PCDATA)>
]>

=== CrispySteak/webTechFinalProject/highscores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "scoreformat.dtd">
<list xmlns="cs.merrimack.edu"
xmlns:xsi=" schema.xsd"
xsi:schemaLocation="http://www.w3schools.com note.xsd">
	<score>
		<username>Joe</username>
		<difficulty>Easy</difficulty>
		<time>20</time>
	</score>
	<score>
		<username>Andrew</username>
		<difficulty>Medium</difficulty>
		<time>41</time>
	</score>
</list>
